/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertEquals(classUnderTest.getGreeting(),"Hello World","app should have a greeting");
    } 
}
